aside completo
PauKaoomi/TallerGrupal pull request #2
Opened 2023-09-09 00:56 UTC by sebastian12acero

Hola, por favor revisar

2023-09-09 20:13 UTC, PauKaoomi requested changes
Recuerda que nos dijeron que no podíamos usar cosas de CSS que no hubiéramos visto en clase que tenga que ver con que los elementos se centren, usaste el display:flex; en la linea 132. El profe ya nos ensaño una opción para centrar elementos y texto en la anterior clase También en el HTML pusiste dos veces el head de HTML, adjunto imagen.
![image](https://github.com/PauKaoomi/TallerGrupal/assets/55894067/fdb6c1e5-cb85-4042-9d84-eae58526f9b7)

2023-09-13 01:02 UTC, ALVARO8-TIGER approved these changes

2023-09-13 01:02 UTC, PauKaoomi approved these changes

2023-09-13 01:03 UTC, ALVARO8-TIGER approved these changes

2023-09-13 01:04 UTC, FSFCR16 approved these changes

2023-09-13 01:06 UTC, merged