Feature/header
PauKaoomi/TallerGrupal pull request #3
Opened 2023-09-09 02:34 UTC by sebastian12acero

header

2023-09-09 20:22 UTC, PauKaoomi requested changes
Recuerda no usar flex qwq

2023-09-12 02:14 UTC, FSFCR16 approved these changes

2023-09-12 02:14 UTC, PauKaoomi approved these changes

2023-09-12 02:18 UTC, ALVARO8-TIGER approved these changes

2023-09-12 02:19 UTC, merged

2023-09-12 02:19 UTC, ALVARO8-TIGER approved these changes