creacion del footer
PauKaoomi/TallerGrupal pull request #4
Opened 2023-09-11 23:30 UTC by ALVARO8-TIGER

se agrega footer ala pagina

2023-09-12 01:42 UTC, sebastian12acero requested changes
Buenas noches segun lo conversado por favor ajustar lo acordado

2023-09-12 01:42 UTC, sebastian12acero commented on index.html
> +<footer>
puedes eliminar esta linea ya que en la siguiente se repite y se le asigna una clase

2023-09-12 01:42 UTC, sebastian12acero commented on index.html
> +            <li>
puedes eliminar esta linea ya que en la siguiente se repite y se le asigna una clase

2023-09-12 01:42 UTC, sebastian12acero commented on style.css
> +  display: flex;
por favor quitar el flex

2023-09-12 01:42 UTC, sebastian12acero commented on index.html
> +
cerrar las listas

2023-09-13 23:40 UTC, ALVARO8-TIGER commented on index.html
> +
ya se reemplazo

2023-09-14 01:41 UTC, PauKaoomi approved these changes

2023-09-14 01:41 UTC, sebastian12acero approved these changes

2023-09-14 01:43 UTC, FSFCR16 approved these changes

2023-09-14 01:44 UTC, merged